apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joke-service
  template:
    metadata:
      labels:
        app: joke-service
    spec:
      containers:
      - name: joke-service
        image: dadjoke-joke-service:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: joke-service
spec:
  selector:
    app: joke-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
